BUILD_DATE := $(shell date +%Y%m%d)
BUILD_TIME := $(shell date +%H%M)

ifndef STREAK_BUILD_TYPE
    STREAK_BUILD_TYPE := UNOFFICIAL
endif

# Set all versions
STREAK_BASE_VERSION := 12.0.0
STREAK_PLATFORM_VERSION := 12
TARGET_PRODUCT_SHORT := $(subst streak_,,$(TARGET_PRODUCT))
STREAK_VERSION := Streak-$(STREAK_BASE_VERSION)-$(STREAK_BUILD_TYPE)-$(TARGET_PRODUCT_SHORT)-$(BUILD_DATE)-$(BUILD_TIME)
ROM_FINGERPRINT := Streak/$(PLATFORM_VERSION)/$(STREAK_BUILD_TYPE)/$(BUILD_DATE)$(BUILD_TIME)

ifeq ($(STREAK_BUILD_TYPE),OFFICIAL)
    PLATFORM_STREAK_VERSION := $(STREAK_BASE_VERSION).REL.$(shell date +%m%d%H%M)
else
    PLATFORM_STREAK_VERSION := $(STREAK_BASE_VERSION).INT.$(shell date +%m%d%H%M)
endif

# Declare it's a ProjectStreak build
STREAK_BUILD := true
